name: Deploy Akamai Config

on:
  push:
    branches:
      - main  # Trigger when the main branch is updated
    paths:
      - src/www.cyberabstract.com.json

jobs:
  new-version-update-ruletree:
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .edgerc credentials
        run: |
          export AKAMAI_EDGERC_PATH=~/.edgerc

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create a new Property Version
        run: |
          source .venv/bin/activate
          python3 src/create_a_new_property_version.py

      - name: Update Property Rule Tree
        run: |
          source .venv/bin/activate
          python3 src/update_property_rule_tree.py

  deploy-to-stage:
    needs: new-version-update-ruletree
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Akamai Staging
        run: |
          source .venv/bin/activate
          python3 src/activate_on_akamai.py staging

  test-on-stage:
    needs: deploy-to-stage
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on staging environment
        run: |
          source .venv/bin/activate
          python3 tests/test_response.py staging

  deploy-to-prod:
    needs: test-on-stage
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Akamai Production
        run: |
          source .venv/bin/activate
          python3 src/activate_on_akamai.py production

  test-on-prod:
    needs: deploy-to-prod
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on production environment
        run: |
          source .venv/bin/activate
          python3 tests/test_response.py production

  cleanup:
    needs: [test-on-prod, test-on-stage, deploy-to-prod, deploy-to-stage, new-version-update-ruletree]
    runs-on: [self-hosted, demo_workflow]
    if: always()  # Run this job even if previous jobs failed
    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      - name: Cleanup .pkl files
        run: |
          find . -name "*.pkl" -type f -delete
