name: Deploy Akamai Config
on:
  push:
    branches:
      - main
    paths:
      - src/gamittal-compute.json  # Trigger only when this file is changed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your Python version

    # Step 3: Install dependencies if needed
    # If you have dependencies for `upload.py`, install them.
    # Otherwise, you can skip this step.
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run upload.py
    - name: Run the upload script
      run: python src/upload.py
