name: Deploy Akamai Config
on:
  push:
    branches:
      - feature/*  # Trigger when a feature branch is updated
    paths:
      - src/www.cyberabstract.com.json  # Trigger only when this file is changed

jobs:
  update-rule-tree:
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .edgerc file
        run: |
          echo "${{ secrets.AKAMAI_EDGERC }}" > ~/.edgerc


      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt  

      # Create a new Property Version
      - name: Create a new Property Version
        run: |
          python3 src/create_a_new_property_version.py 

      - name: Update Property Rule Tree
        run: |
          python3 src/update_property_rule_tree.py 

  deploy-to-stage:
    needs: update-rule-tree
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt  

      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Deploy to Akamai Staging
      - name: Deploy to Akamai Staging
        run: |
          python3 src/activate_on_stage.py  # Using system-installed Python

  test-on-stage:
    needs: deploy-to-stage  # This job will only run if 'deploy-to-stage' is successful
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt 

      # Step: Run pytest to test on staging environment
      - name: Run pytest on staging environment
        run: |
          pytest tests/test_stage.py  # Run your pytest file to verify on staging
        working-directory: ${{ github.workspace }}




  merge-to-main:
    needs: test-on-stage
    if: success()  # This ensures that this job runs only if the previous jobs are successful
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Merge the feature branch into the main branch
      - name: Merge feature branch into main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge ${{ github.head_ref }}  # Merge feature branch into main
          git push origin main  # Push the changes to the main branch

      # Delete the feature branch after merging
      - name: Delete feature branch
        run: |
          git push origin --delete ${{ github.head_ref }}  # Delete the feature branch on the remote

  deploy-to-production:
    needs: merge-to-main  # This job will run only if the merge is successful
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Deploy to Akamai Production
      - name: Deploy to Akamai Production
        run: |
          python3 src/activate_on_prod.py  # Using system-installed Python to deploy to production

      # Step: Run test script and handle status code ranges
      - name: Run prod test script
        id: run_test
        run: |
          python3 tests/test_prod.py
