name: Deploy Akamai Config

on:
  push:
    branches:
      - main  # Trigger when a feature branch is updated
#    paths:
#      - src/*.json  # Trigger only when this file is changed

jobs:
  update-rule-tree:
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .edgerc credentials
        run: |
          export AKAMAI_EDGERC_PATH=~/.edgerc

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Create a new Property Version
        run: |
          python3 src/create_a_new_property_version.py

      - name: Update Property Rule Tree
        run: |
          python3 src/update_property_rule_tree.py

  deploy-to-stage:
    needs: update-rule-tree
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      # Step: Deploy to Akamai Staging
      - name: Deploy to Akamai Staging
        run: |
          python3 src/activate_on_akamai.py staging  # Pass 'staging' to the common script

  test-on-stage:
    needs: deploy-to-stage
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      # Step: Run tests on staging environment
      - name: Run tests on staging environment
        run: |
          python3 src/test_response.py staging  # Test staging environment using the unified script

  deploy-to-prod:
    needs: test-on-stage
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt 

      # Step: Deploy to Akamai Production
      - name: Deploy to Akamai Production
        run: |
          python3 src/activate_on_akamai.py production  # Pass 'production' to the common script

  test-on-prod:
    needs: deploy-to-prod
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      # Step: Run tests on production environment
      - name: Run tests on production environment
        run: |
          python3 src/test_response.py production  # Test production environment using the unified script

  cleanup:
    # This job will only run after all other jobs have completed
    needs: [test-on-prod, test-on-stage, deploy-to-prod, deploy-to-stage, update-rule-tree]
    runs-on: [self-hosted, demo_workflow]
    if: always()  # Run this job even if previous jobs failed
    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      # Step: Cleanup .pkl files
      - name: Cleanup .pkl files
        run: |
          find . -name "*.pkl" -type f -delete
