name: Deploy Akamai Config
on:
  push:
    branches:
      - feature/*  # Trigger when a feature branch is updated
    paths:
      - src/gamittal-compute.json  # Trigger only when this file is changed

jobs:
  update-rule-tree:
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .edgerc file
        run: |
          echo "${{ secrets.AKAMAI_EDGERC }}" > ~/.edgerc


      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt  # Using system-installed Python 3.12.0

#      # Create a new Property Version
#      - name: Create a new Property Version
#        run: |
#          python3 src/create_a_new_property_version.py  # Using system-installed Python

      - name: Update Property Rule Tree
        run: |
          python3 src/update_property_rule_tree.py  # Using system-installed Python

  deploy-to-stage:
    needs: update-rule-tree
    runs-on: [self-hosted, demo_workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step: Deploy to Akamai Staging
      - name: Deploy to Akamai Staging
        run: |
          python3 src/activate_on_stage.py  # Using system-installed Python

      # Step: Run test script
      - name: Run test script
        run: |
          python3 src/test_stage.py  # Using system-installed Python
